"""LLM-powered family task intent resolver.

Parses go-pick-return instructions using DeepSeek, constrained to approved
catalog place/object IDs.  Falls back to the rule-based split-and-match parser
when the API key is missing or the call fails.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
import os
import sys
from pathlib import Path
from typing import Any, Mapping

LINGBOT_SRC = Path(__file__).resolve().parents[1] / "lingbot_semantic_nav/src"
if str(LINGBOT_SRC) not in sys.path:
    sys.path.insert(0, str(LINGBOT_SRC))

from lingbot_nav.config import load_dotenv
from lingbot_nav.errors import ProviderError
from lingbot_nav.intent import _JsonHttpClient

# Rule-based fallback parser --------------------------------------------------
from g1d_dual_brain_agent.planner import (  # noqa: E402
    _match_catalog_item,
    _split_long_instruction,
)


# ---------------------------------------------------------------------------
# These are scene-reviewed functional descriptions.  They are the *only*
# semantic hints the LLM receives beyond the catalog aliases.  Adding a new
# functional hint for an existing place is a content change, not a code change.
# ---------------------------------------------------------------------------
_PLACE_FUNCTIONS: dict[str, list[str]] = {
    "living_room_sofa": ["休息", "坐下", "会客", "看电视"],
    "bedroom_bed": ["睡觉", "睡眠", "休息", "躺下"],
    "dining_area": ["吃饭", "用餐", "喝水"],
    "kitchen_counter": ["做饭", "准备食物", "厨房操作"],
    "living_room_center": ["活动", "站在客厅中央", "客厅中间"],
    "media_cabinet_front": ["看电视", "拿遥控器", "电视柜"],
    "dining_table_south": ["餐桌另一侧", "用餐", "取餐具"],
    "kitchen_entrance": ["进入厨房", "厨房门口", "准备做饭"],
    "bedroom_entrance": ["进入卧室", "卧室门口", "准备睡觉"],
}


@dataclass(frozen=True)
class TaskResolution:
    """A single structured result that the runner / dashboard consumes."""

    task_type: str  # "go_pick_return" | "vln_navigation" | "unknown"
    parser: str  # "deepseek" | "rule"
    confidence: float
    outbound_place_id: str = ""
    object_id: str = ""
    return_place_id: str = ""
    destination_place_id: str = ""


class FamilyTaskIntentResolver:
    """Use a constrained LLM to parse go-pick-return instructions.

    The LLM may **only** select IDs from the supplied catalogs.  Coordinates,
    paths, and manipulation parameters are never generated by the model.

    When the API key is missing or the HTTP call fails the resolver silently
    degrades to the deterministic rule parser.
    """

    def __init__(
        self,
        places_catalog: Mapping[str, Any],
        objects_catalog: Mapping[str, Any],
        *,
        provider: str = "deepseek",
        allow_rule_fallback: bool = True,
    ) -> None:
        load_dotenv()
        self.places_catalog = dict(places_catalog)
        self.objects_catalog = dict(objects_catalog)
        self.provider = provider.strip().casefold()
        self.allow_rule_fallback = bool(allow_rule_fallback)

        if self.provider == "deepseek":
            self._api_key = os.getenv("DEEPSEEK_API_KEY", "")
            self._base_url = os.getenv(
                "DEEPSEEK_BASE_URL", "https://api.deepseek.com"
            )
            self._model = os.getenv("DEEPSEEK_MODEL", "deepseek-v4-flash")
        else:
            self._api_key = os.getenv("OPENAI_API_KEY", "")
            self._base_url = os.getenv(
                "OPENAI_BASE_URL", "https://api.openai.com/v1"
            )
            self._model = os.getenv("OPENAI_MODEL", "gpt-5.4-mini")

        self._client = _JsonHttpClient()
        self.name = self.provider

    # ------------------------------------------------------------------ public

    def resolve(self, command: str) -> TaskResolution:
        """Parse *command* into a structured task.

        Returns ``TaskResolution(task_type="unknown", …)`` only when every
        strategy (LLM and rule) fails to match the catalog.
        """
        if not command.strip():
            return TaskResolution("unknown", self.name, 0.0)

        if not self._api_key:
            if not self.allow_rule_fallback:
                raise ProviderError(f"{self.name} API key is missing")
            return self._resolve_rule(command)

        try:
            return self._resolve_llm(command)
        except (ProviderError, OSError, ValueError) as exc:
            if not self.allow_rule_fallback:
                raise ProviderError(
                    f"{self.name} intent resolution failed: {exc}"
                ) from exc
            # Degrade gracefully – a missing key or a network blip must never
            # block the entire pipeline.
            rule_result = self._resolve_rule(command)
            return TaskResolution(
                rule_result.task_type,
                f"{self.name}+rule-fallback",
                rule_result.confidence,
                rule_result.outbound_place_id,
                rule_result.object_id,
                rule_result.return_place_id,
                rule_result.destination_place_id,
            )

    # -------------------------------------------------------------- internal

    def _build_catalog_payload(self) -> dict[str, list[dict[str, Any]]]:
        """Return a minimal JSON-serialisable catalog for the system prompt."""

        places: list[dict[str, Any]] = []
        for item in self.places_catalog.get("places", []):
            pid = str(item.get("id") or item.get("place_id") or "").strip()
            if not pid:
                continue
            entry: dict[str, Any] = {
                "id": pid,
                "name": str(item.get("name", "")).strip(),
                "aliases": [
                    a
                    for a in (item.get("aliases") or [])
                    if isinstance(a, str) and a.strip()
                ],
            }
            funcs = (
                item.get("metadata", {})
                .get("functional_descriptions", [])
                if isinstance(item.get("metadata"), Mapping)
                else []
            )
            if not funcs:
                funcs = _PLACE_FUNCTIONS.get(pid, [])
            if funcs:
                entry["功能"] = [str(f).strip() for f in funcs if str(f).strip()]
            places.append(entry)

        objects: list[dict[str, Any]] = []
        for item in self.objects_catalog.get("objects", []):
            oid = str(
                item.get("object_id") or item.get("id") or ""
            ).strip()
            if not oid:
                continue
            objects.append(
                {
                    "id": oid,
                    "name": str(item.get("name", "")).strip(),
                    "label": str(item.get("source_label", "")).strip(),
                    "aliases": [
                        a
                        for a in (item.get("aliases") or [])
                        if isinstance(a, str) and a.strip()
                    ],
                    "located_at_place_id": str(
                        item.get("home_place_id", "")
                    ).strip(),
                }
            )

        return {"places": places, "objects": objects}

    def _resolve_llm(self, command: str) -> TaskResolution:
        catalog = self._build_catalog_payload()
        catalog_text = json.dumps(catalog, ensure_ascii=False, indent=2)

        system_prompt = (
            "你是家庭服务机器人的任务解析器。将用户的自然语言指令分解为结构化任务。\n\n"
            f"当前可用的地点和物体目录（只能从中选择 id，严禁编造）：\n{catalog_text}\n\n"
            "任务类型判断：\n"
            "- go_pick_return: 用户要求【去某地 → 拿某物 → 回到某地】\n"
            "- vln_navigation: 用户只要求去一个地点\n"
            "- unknown: 无法匹配任何目录条目\n\n"
            "语义匹配规则（根据名称、别名和功能描述推断，不要求用户逐字说出目录词）：\n"
            "- 功能描述中有【做饭/准备食物】的地点 → 【做饭的地方/煮饭的地方】\n"
            "- 功能描述中有【吃饭/用餐】的地点 → 【吃饭的地方/用餐的地方】\n"
            "- 功能描述中有【睡觉/睡眠】的地点 → 【睡觉的地方/卧室】\n"
            "- 功能描述中有【休息/坐下】的地点 → 【休息的地方/能坐的地方/客厅】\n"
            "- 物体名称/别名/标签中有【杯】的 → 【杯子/水杯/咖啡杯】\n"
            "- go_pick_return 的 outbound_place_id 必须使用目标物体的 "
            "located_at_place_id；物体位置来自审核目录，不允许猜测或沿用其他物体的位置\n"
            "- 此规则只用于最终目的地或目标物体，不能虚构不存在的 id\n\n"
            "输出严格 JSON（不要附加任何解释性文字）：\n"
            '{"task_type": "go_pick_return"|"vln_navigation"|"unknown", '
            '"outbound_place_id": "", '
            '"object_id": "", '
            '"return_place_id": "", '
            '"destination_place_id": "", '
            '"confidence": 0.0-1.0, '
            '"思考": "简要说明匹配理由（最多一句话）"}'
        )

        payload = {
            "model": self._model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": command},
            ],
            "thinking": {"type": "disabled"},
            "response_format": {"type": "json_object"},
            "max_tokens": 500,
            "stream": False,
        }

        response = self._client.post(
            f"{self._base_url}/chat/completions",
            self._api_key,
            payload,
        )

        try:
            content: str = response["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as exc:
            raise ProviderError("LLM response has no message content") from exc

        if not content or not content.strip():
            raise ProviderError("LLM returned empty content")

        try:
            value: dict[str, Any] = json.loads(content)
        except json.JSONDecodeError as exc:
            raise ProviderError("LLM returned invalid JSON") from exc

        task_type = str(value.get("task_type", "unknown")).strip()
        confidence = float(value.get("confidence", 0.0))

        # --- go-pick-return branch ------------------------------------------
        if task_type == "go_pick_return":
            outbound_id = self._validate_place(
                str(value.get("outbound_place_id", "")).strip()
            )
            object_id = self._validate_object(
                str(value.get("object_id", "")).strip()
            )
            object_home = self._object_home_place(object_id)
            if object_home:
                outbound_id = object_home
            return_id = self._validate_place(
                str(value.get("return_place_id", "")).strip()
            )

            if outbound_id and object_id and return_id:
                return TaskResolution(
                    task_type="go_pick_return",
                    parser=self.name,
                    confidence=confidence,
                    outbound_place_id=outbound_id,
                    object_id=object_id,
                    return_place_id=return_id,
                )

        # --- single-place navigation branch ---------------------------------
        dest_id = str(value.get("destination_place_id", "")).strip()
        if not dest_id:
            # The model may have put the destination in the wrong field.
            for field in ("outbound_place_id", "return_place_id"):
                candidate = str(value.get(field, "")).strip()
                if candidate:
                    dest_id = candidate
                    break

        dest_id = self._validate_place(dest_id)
        if dest_id:
            return TaskResolution(
                task_type="vln_navigation",
                parser=self.name,
                confidence=confidence,
                destination_place_id=dest_id,
            )

        raise ProviderError(
            f"LLM returned no valid catalog ID: {json.dumps(value, ensure_ascii=False)}"
        )

    # -------------------------------------------------------- catalog guards

    def _validate_place(self, place_id: str) -> str:
        """Return the canonical place id or '' if not in the catalog."""
        if not place_id:
            return ""
        normalized = place_id.strip().casefold()
        for item in self.places_catalog.get("places", []):
            pid = str(item.get("id") or item.get("place_id") or "").strip()
            if not pid:
                continue
            if pid.casefold() == normalized:
                return pid
            if str(item.get("name", "")).strip().casefold() == normalized:
                return pid
            for alias in item.get("aliases", []):
                if isinstance(alias, str) and alias.strip().casefold() == normalized:
                    return pid
        return ""

    def _validate_object(self, object_id: str) -> str:
        """Return the canonical object id or '' if not in the catalog."""
        if not object_id:
            return ""
        normalized = object_id.strip().casefold()
        for item in self.objects_catalog.get("objects", []):
            oid = str(
                item.get("object_id") or item.get("id") or ""
            ).strip()
            if not oid:
                continue
            if oid.casefold() == normalized:
                return oid
            if str(item.get("source_label", "")).strip().casefold() == normalized:
                return oid
            if str(item.get("name", "")).strip().casefold() == normalized:
                return oid
            for alias in item.get("aliases", []):
                if isinstance(alias, str) and alias.strip().casefold() == normalized:
                    return oid
        return ""

    def _object_home_place(self, object_id: str) -> str:
        """Return the reviewed navigation region that contains an object."""
        if not object_id:
            return ""
        for item in self.objects_catalog.get("objects", []):
            oid = str(item.get("object_id") or item.get("id") or "").strip()
            if oid != object_id:
                continue
            home = self._validate_place(str(item.get("home_place_id", "")))
            return home
        return ""

    # -------------------------------------------------------- rule fallback

    def _resolve_rule(self, command: str) -> TaskResolution:
        """Deterministic fallback identical to the pre-LLM behaviour."""

        # -- try go-pick-return split ----------------------------------------
        try:
            outbound_phrase, object_phrase, return_phrase = (
                _split_long_instruction(command)
            )
            outbound = _match_catalog_item(
                outbound_phrase,
                [
                    it
                    for it in self.places_catalog.get("places", [])
                    if isinstance(it, Mapping)
                ],
                kind="地点",
            )
            target = _match_catalog_item(
                object_phrase,
                [
                    it
                    for it in self.objects_catalog.get("objects", [])
                    if isinstance(it, Mapping)
                ],
                kind="对象",
            )
            return_place = _match_catalog_item(
                return_phrase,
                [
                    it
                    for it in self.places_catalog.get("places", [])
                    if isinstance(it, Mapping)
                ],
                kind="地点",
            )

            return TaskResolution(
                task_type="go_pick_return",
                parser="rule",
                confidence=0.95,
                outbound_place_id=(
                    self._object_home_place(
                        str(target.get("object_id") or target.get("id", ""))
                    )
                    or str(outbound.get("id") or outbound.get("place_id", ""))
                ),
                object_id=str(
                    target.get("object_id") or target.get("id", "")
                ),
                return_place_id=str(
                    return_place.get("id")
                    or return_place.get("place_id", "")
                ),
            )
        except (ValueError, KeyError, TypeError):
            pass

        # -- try single-place match ------------------------------------------
        try:
            match = _match_catalog_item(
                command,
                [
                    it
                    for it in self.places_catalog.get("places", [])
                    if isinstance(it, Mapping)
                ],
                kind="地点",
            )
            place_id = str(match.get("id") or match.get("place_id", ""))
            if place_id:
                return TaskResolution(
                    task_type="vln_navigation",
                    parser="rule",
                    confidence=0.95,
                    destination_place_id=place_id,
                )
        except (ValueError, KeyError, TypeError):
            pass

        return TaskResolution("unknown", "rule", 0.0)


__all__ = ["FamilyTaskIntentResolver", "TaskResolution"]
